from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
from collections import Counter
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .types import SVD_REPORT_SCHEMA_VERSION


DEFAULT_MODEL_SPEC = "unsloth/Qwen3.5-35B-A3B-GGUF:Q4_K_M"


class MolrPhase0Error(RuntimeError):
    """Raised when a Phase-0 artifact operation fails."""


def add_common_archive_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--svd-report",
        required=True,
        help="Path to existing svd_report.json generated by scripts/analyze_moe_svd.py.",
    )
    parser.add_argument(
        "--run-dir",
        required=True,
        help="Output directory for archived Phase-0 artifacts.",
    )
    parser.add_argument(
        "--model",
        default=DEFAULT_MODEL_SPEC,
        help=(
            "Model spec this archive is expected to describe. "
            f"Default: {DEFAULT_MODEL_SPEC}"
        ),
    )
    parser.add_argument(
        "--workers",
        type=int,
        default=16,
        help="Workers intended for analyze_moe_svd.py command capture. Default: 16.",
    )
    parser.add_argument(
        "--blas-threads",
        type=int,
        default=1,
        help="BLAS threads intended for analyze_moe_svd.py command capture. Default: 1.",
    )
    parser.add_argument(
        "--allow-model-mismatch",
        action="store_true",
        help="Allow archiving even if svd_report.run.model_spec does not match --model.",
    )
    parser.add_argument(
        "--notes",
        default="",
        help="Optional operator note included in run metadata.",
    )


def validate_common_archive_args(args: argparse.Namespace, parser: argparse.ArgumentParser) -> None:
    if args.workers <= 0:
        parser.error("--workers must be > 0.")
    if args.blas_threads <= 0:
        parser.error("--blas-threads must be > 0.")


def load_json(path: Path) -> dict[str, Any]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:
        raise MolrPhase0Error(f"Failed to read JSON '{path}': {exc}") from exc


def save_json(path: Path, payload: dict[str, Any]) -> None:
    tmp_path = path.with_suffix(path.suffix + ".tmp")
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp_path.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
        tmp_path.replace(path)
    except Exception as exc:
        raise MolrPhase0Error(f"Failed to write JSON '{path}': {exc}") from exc


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as f:
        while True:
            chunk = f.read(1024 * 1024)
            if not chunk:
                break
            digest.update(chunk)
    return digest.hexdigest()


def _safe_git_output(command: list[str]) -> str | None:
    try:
        out = subprocess.check_output(command, stderr=subprocess.DEVNULL, text=True).strip()
        return out or None
    except Exception:
        return None


def git_commit() -> str | None:
    return _safe_git_output(["git", "rev-parse", "HEAD"])


def git_branch() -> str | None:
    return _safe_git_output(["git", "rev-parse", "--abbrev-ref", "HEAD"])


def now_utc_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def quantization_from_model_spec(model_spec: str) -> str | None:
    if ":" not in model_spec:
        return None
    quant = model_spec.rsplit(":", 1)[1].strip()
    return quant or None


@dataclass(slots=True)
class CoverageSummary:
    total_tensors: int
    candidates: int
    analyzed: int
    failed: int
    coverage_ratio_candidates_vs_total: float
    coverage_ratio_analyzed_vs_candidates: float
    unique_layer_count: int
    unique_expert_count: int
    role_histogram: dict[str, int]
    layer_histogram: dict[str, int]
    expert_histogram_sample: dict[str, int]
    plausibility_status: str
    plausibility_reasons: list[str]

    def to_dict(self) -> dict[str, Any]:
        return {
            "total_tensors": self.total_tensors,
            "candidates": self.candidates,
            "analyzed": self.analyzed,
            "failed": self.failed,
            "coverage_ratio_candidates_vs_total": self.coverage_ratio_candidates_vs_total,
            "coverage_ratio_analyzed_vs_candidates": self.coverage_ratio_analyzed_vs_candidates,
            "unique_layer_count": self.unique_layer_count,
            "unique_expert_count": self.unique_expert_count,
            "role_histogram": self.role_histogram,
            "layer_histogram": self.layer_histogram,
            "expert_histogram_sample": self.expert_histogram_sample,
            "plausibility_status": self.plausibility_status,
            "plausibility_reasons": self.plausibility_reasons,
        }


def _to_int(value: Any, default: int = 0) -> int:
    try:
        return int(value)
    except Exception:
        return default


def _ratio(num: int, den: int) -> float:
    if den <= 0:
        return 0.0
    return float(num) / float(den)


def _sample_counter(counter: Counter[Any], limit: int = 12) -> dict[str, int]:
    items = sorted(counter.items(), key=lambda kv: (-kv[1], kv[0]))[:limit]
    return {str(key): int(value) for key, value in items}


def build_coverage_summary(svd_report: dict[str, Any]) -> CoverageSummary:
    discovery = svd_report.get("discovery", {})
    summary = svd_report.get("summary", {})
    counts = summary.get("counts", {})
    per_matrix = svd_report.get("per_matrix", [])
    failed_matrices = svd_report.get("failed_matrices", [])

    total_tensors = _to_int(counts.get("total_tensors", discovery.get("total_tensors", 0)))
    candidates = _to_int(counts.get("candidates", discovery.get("expert_candidate_tensors", 0)))
    analyzed = _to_int(counts.get("analyzed", len(per_matrix)))
    failed = len(failed_matrices)

    role_counter: Counter[str] = Counter()
    layer_counter: Counter[str] = Counter()
    expert_counter: Counter[str] = Counter()

    for record in per_matrix:
        role_counter[str(record.get("role") or "unknown")] += 1
        layer_counter[str(record.get("layer") if record.get("layer") is not None else "unknown")] += 1
        if record.get("expert") is not None:
            expert_counter[str(record.get("expert"))] += 1

    unique_layers = {r.get("layer") for r in per_matrix if r.get("layer") is not None}
    unique_experts = {r.get("expert") for r in per_matrix if r.get("expert") is not None}

    reasons: list[str] = []
    status = "pass"
    if candidates <= 0:
        status = "fail"
        reasons.append("No expert candidate tensors were discovered.")
    if analyzed <= 0:
        status = "fail"
        reasons.append("No expert matrices were analyzed.")
    analyzed_vs_candidates = _ratio(analyzed, candidates)
    if candidates > 0 and analyzed_vs_candidates < 0.5:
        status = "warn" if status == "pass" else status
        reasons.append(
            "Less than 50% of candidate matrices were analyzed; inspect failed/skipped reasons.",
        )
    if len(unique_layers) == 0:
        status = "warn" if status == "pass" else status
        reasons.append("No layer metadata present in analyzed matrices.")
    if len(unique_experts) == 0:
        status = "warn" if status == "pass" else status
        reasons.append("No expert metadata present in analyzed matrices.")

    return CoverageSummary(
        total_tensors=total_tensors,
        candidates=candidates,
        analyzed=analyzed,
        failed=failed,
        coverage_ratio_candidates_vs_total=_ratio(candidates, total_tensors),
        coverage_ratio_analyzed_vs_candidates=analyzed_vs_candidates,
        unique_layer_count=len(unique_layers),
        unique_expert_count=len(unique_experts),
        role_histogram=dict(sorted(role_counter.items())),
        layer_histogram=_sample_counter(layer_counter, limit=32),
        expert_histogram_sample=_sample_counter(expert_counter, limit=16),
        plausibility_status=status,
        plausibility_reasons=reasons,
    )


def build_phase0_run_metadata(
    *,
    model_spec: str,
    workers: int,
    blas_threads: int,
    svd_report_path: Path,
    svd_report_sha256: str,
    svd_report_schema_version: str,
    coverage: CoverageSummary,
    operator_notes: str,
) -> dict[str, Any]:
    command = [
        "python",
        "scripts/analyze_moe_svd.py",
        "--model",
        model_spec,
        "--out-json",
        "<run>/svd_report.json",
        "--full-svd",
        "--workers",
        str(workers),
        "--blas-threads",
        str(blas_threads),
    ]

    quantization = quantization_from_model_spec(model_spec)
    quant_caveat = None
    if quantization is not None and quantization.upper() == "Q4_K_M":
        quant_caveat = (
            "Q4_K_M quantization may bias singular spectra and explained-energy metrics "
            "versus higher-precision checkpoints (FP16/BF16)."
        )

    return {
        "schema_version": "phase0_run_metadata.v1",
        "created_at_utc": now_utc_iso(),
        "phase": "phase0",
        "model_spec": model_spec,
        "quantization": quantization,
        "analysis_command_template": " ".join(command),
        "analysis_command_argv": command,
        "analysis_fidelity_mode": "full_svd",
        "workers": workers,
        "blas_threads": blas_threads,
        "svd_report": {
            "path": str(svd_report_path),
            "sha256": svd_report_sha256,
            "schema_version": svd_report_schema_version,
        },
        "coverage_check": coverage.to_dict(),
        "quantization_caveat": quant_caveat,
        "notes": operator_notes,
        "environment": {
            "hostname": os.uname().nodename,
            "git_commit": git_commit(),
            "git_branch": git_branch(),
            "python_executable": os.path.realpath(sys.executable),
        },
    }


def ensure_expected_svd_report(
    *,
    svd_report: dict[str, Any],
    expected_model_spec: str,
    allow_model_mismatch: bool,
) -> None:
    schema_version = str(svd_report.get("schema_version") or "")
    if schema_version != SVD_REPORT_SCHEMA_VERSION:
        raise MolrPhase0Error(
            f"Unexpected svd_report schema_version='{schema_version}', expected '{SVD_REPORT_SCHEMA_VERSION}'.",
        )

    run = svd_report.get("run", {})
    model_spec = str(run.get("model_spec") or "")
    if not allow_model_mismatch and model_spec != expected_model_spec:
        raise MolrPhase0Error(
            "svd_report run.model_spec mismatch: "
            f"expected '{expected_model_spec}', got '{model_spec}'. "
            "Use --allow-model-mismatch only if this was intentional."
        )

    fidelity_mode = str(run.get("fidelity_mode") or "")
    if fidelity_mode != "full_svd":
        raise MolrPhase0Error(
            f"svd_report run.fidelity_mode must be 'full_svd' for Phase-0, got '{fidelity_mode}'.",
        )


def stage_phase0_artifacts(
    *,
    svd_report_path: Path,
    run_dir: Path,
    run_metadata: dict[str, Any],
) -> list[Path]:
    run_dir.mkdir(parents=True, exist_ok=True)

    archived_svd = run_dir / "svd_report.json"
    archived_metadata = run_dir / "run_metadata.json"
    archived_manifest = run_dir / "phase0_manifest.json"

    try:
        archived_svd.write_text(svd_report_path.read_text(encoding="utf-8"), encoding="utf-8")
    except Exception as exc:
        raise MolrPhase0Error(f"Failed to archive svd_report.json: {exc}") from exc

    save_json(archived_metadata, run_metadata)

    manifest = {
        "schema_version": "phase0_manifest.v1",
        "created_at_utc": now_utc_iso(),
        "artifacts": [
            {
                "name": "svd_report.json",
                "path": str(archived_svd),
                "sha256": sha256_file(archived_svd),
            },
            {
                "name": "run_metadata.json",
                "path": str(archived_metadata),
                "sha256": sha256_file(archived_metadata),
            },
        ],
    }
    save_json(archived_manifest, manifest)

    return [archived_svd, archived_metadata, archived_manifest]
