#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

if __package__ is None or __package__ == "":
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from molr.artifacts import (
    MolrPhase0Error,
    build_coverage_summary,
    ensure_expected_svd_report,
    DEFAULT_MODEL_SPEC,
    load_json,
)


EXIT_OK = 0
EXIT_CHECK_FAILED = 2


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Validate Phase-0 svd_report.json for MoLR baseline checklist intent "
            "(schema/model checks, coverage plausibility, quantization caveat visibility)."
        ),
    )
    parser.add_argument(
        "--svd-report",
        required=True,
        help="Path to svd_report.json generated by scripts/analyze_moe_svd.py.",
    )
    parser.add_argument(
        "--model",
        default=DEFAULT_MODEL_SPEC,
        help=(
            "Model spec this report is expected to describe. "
            f"Default: {DEFAULT_MODEL_SPEC}"
        ),
    )
    parser.add_argument(
        "--allow-model-mismatch",
        action="store_true",
        help="Allow validation even if svd_report.run.model_spec does not match --model.",
    )
    parser.add_argument(
        "--strict-coverage",
        action="store_true",
        help="Return failure if plausibility status is not pass.",
    )
    parser.add_argument(
        "--out-json",
        default="",
        help="Optional path to write a machine-readable check result JSON.",
    )
    args = parser.parse_args(argv)
    return args


def _build_check_result(svd_report: dict, coverage_status: str, coverage_reasons: list[str]) -> dict:
    run = svd_report.get("run", {})
    caveats = list(svd_report.get("assumptions_and_caveats", []))
    mentions_q4 = any("Q4_K_M" in str(item) for item in caveats)
    return {
        "schema_version": "phase0_svd_check.v1",
        "model_spec": run.get("model_spec"),
        "fidelity_mode": run.get("fidelity_mode"),
        "workers": run.get("workers"),
        "blas_threads": run.get("blas_threads"),
        "coverage": {
            "status": coverage_status,
            "reasons": coverage_reasons,
        },
        "quantization_caveat_present": mentions_q4,
        "assumptions_and_caveats": caveats,
    }


def main(argv: list[str]) -> int:
    try:
        args = parse_args(argv)
        svd_report_path = Path(args.svd_report).expanduser().resolve()
        if not svd_report_path.is_file():
            raise MolrPhase0Error(f"svd_report path is not a file: '{svd_report_path}'")

        svd_report = load_json(svd_report_path)
        ensure_expected_svd_report(
            svd_report=svd_report,
            expected_model_spec=args.model,
            allow_model_mismatch=args.allow_model_mismatch,
        )

        coverage = build_coverage_summary(svd_report)
        result = _build_check_result(
            svd_report=svd_report,
            coverage_status=coverage.plausibility_status,
            coverage_reasons=coverage.plausibility_reasons,
        )

        print("[phase0-check] svd_report validation")
        print(
            f"[phase0-check] model={result['model_spec']} mode={result['fidelity_mode']} "
            f"workers={result['workers']} blas_threads={result['blas_threads']}",
        )
        print(
            "[phase0-check] coverage: "
            f"status={coverage.plausibility_status} "
            f"candidates={coverage.candidates} analyzed={coverage.analyzed} "
            f"unique_layers={coverage.unique_layer_count} unique_experts={coverage.unique_expert_count}",
        )
        if coverage.plausibility_reasons:
            print("[phase0-check] coverage notes:")
            for reason in coverage.plausibility_reasons:
                print(f"  - {reason}")

        print(
            "[phase0-check] quantization caveat in report assumptions: "
            f"{'yes' if result['quantization_caveat_present'] else 'no'}",
        )

        if args.out_json:
            out_path = Path(args.out_json).expanduser().resolve()
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(json.dumps(result, indent=2, sort_keys=True), encoding="utf-8")
            print(f"[phase0-check] wrote: {out_path}")

        if args.strict_coverage and coverage.plausibility_status != "pass":
            return EXIT_CHECK_FAILED

        return EXIT_OK

    except MolrPhase0Error as exc:
        print(f"[error:phase0-check] {exc}", file=sys.stderr)
        return EXIT_CHECK_FAILED


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
